import { desc } from "framer-motion/client";
import {
  Aerospace76105RCAirplane,
  AerospaceSlingshotTech,
  AerospaceTech,
  AerospaceTinyWhoop,
  AerospaceWaterpoweredbottleRocket,
  AerospaceWingman,
  BountyHunter,
  CiviconBridgeMaking,
  CiviconCanvaDesign,
  CiviconEscapeRoom,
  CiviconWheresTheMystery,
  CompetitiveProgramming,
  Designovate,
  DigTheWeb,
  EnergyCircuitCraft,
  EnergyElectrovia,
  EnergyGameMania,
  EnergyLineFollower,
  HumanLudo,
  PVPGaming,
  RescueRangers,
  SAEFrameForge,
  SAELeadTheBeast,
  SensorSyncSymposium,
  SpectrumCirKit,
  SpectrumDesignAthon,
  SpectrumEditExpo,
  SpectrumGameCraft,
  SpectrumRoboSoccer,
  SpectrumSpecMoji,
  SpectrumTechMeme,
  SpectrumUncannyCodeQuest,
  WearableTech,
  ZairzaBountyHunter,
  ZairzaHumanLudo,
  ZairzaPVPGaming,
  ZairzaRescueRangers,
  ZairzaSensorSync,
  ZairzaWearableTech,
} from "./assets";

import aerospacelogo from "./assets/aerologo.png";
import zairzalogo from "./assets/zairzalogo.webp";
import spectrumlogo from "./assets/spectrumlogo.png";
import saelogo from "./assets/saelogo.png";
import biozologo from "./assets/biozologo.png";
import civiconlogo from "./assets/civiconlogo.png";
import energylogo from "./assets/energylogo.png";


export const events28 = [
  {
    eventName: "Bounty Hunter",
    description:
      "In Bounty Hunter, participants identify and report bugs in software within a time limit. Bugs must be documented with clear details and solutions. Points are awarded for severity, complexity, and quality. The team finding the most valid bugs wins. Focus on collaboration, detail, and problem-solving.",
    date: "2025-02-15",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    clubName: "Zairza",
    day: "Day 1",
    reglink: "https://www.google.com",
    image: ZairzaBountyHunter,
  },
  {
    eventName: "Dig The Web",
    description:
      "In Dig the Web, participants solve riddles or clues using the internet within a time limit. Points are earned for correct answers, with difficulty increasing. Speed, accuracy, and resourcefulness are crucial. The first to complete wins. Collaboration and critical thinking are key, using only legitimate sources.",
    date: "2025-02-15",
    startTime: "2:00 PM",
    endTime: "5:00 PM",
    clubName: "Zairza",
    day: "Day 1",
    image: DigTheWeb,
    reglink: "",
  },
  {
    eventName: "Human Ludo",
    description:
      "In Human Ludo, participants act as game pieces on a life-sized grid. Teams roll a giant dice to move, aiming to get all players to their home base while avoiding obstacles and opponents. Landing on an opponent's space sends them back to the start. Teamwork and strategy are key to winning.",
    date: "2025-02-16",
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    clubName: "Zairza",
    day: "Day 1",
    image: ZairzaHumanLudo,
    reglink: "",
  },
  {
    eventName: "SensorSync Symposium",
    description:
      "In the Sensor Sync Symposium, teams of four solve a problem using provided sensors like temperature or motion sensors. They must design a functional system in 60 minutes, judged on innovation, functionality, and practicality. Additional tools are allowed, but the core solution must use the provided sensors. Time management is key!",
    date: "2025-02-16",
    startTime: "1:00 PM",
    endTime: "4:00 PM",
    clubName: "Zairza",
    day: "Day 1",
    image: ZairzaSensorSync,
    reglink: "",
  },
  {
    eventName: "Competitve Programming",
    description:
      "In Competitive Programming, participants work solo or in pairs to solve a beginner-level algorithm problem within a time limit. In pairs, one codes while the other guides and debugs. Points are awarded for correctness and efficiency. Teamwork, problem-solving, and time management are key. The best solution wins.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Zairza",
    day: "Day 1",
    image: CompetitiveProgramming,
    reglink: "",
  },
  {
    eventName: "Cir-Kit",
    description:
      "Welcome to Cir-Kit, the electrifying event where circuits, sensors, and code come together in a race against time! In this hands-on challenge, participants will assemble cutting-edge hardware projects using Arduino and sensors. The catch? The hardware and code are pre-loaded, so you’ll focus purely on the assembly and wiring. It’s a test of precision, teamwork, and speed—who will be the first to power up a fully functional project? ",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumCirKit,
    reglink: "",
  },
  {
    eventName: "Design-A-Thon",
    description:
      "Welcome to Design-Athon, the place where pixels meet playfulness and technology meets artistry! Think you’ve got what it takes to create a jawdropping design that’s as sharp as your coding skills? Get ready to flex your creative muscles with AI tools and editing software to make the ultimate techinfused masterpiece.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumDesignAthon,
    reglink: "",
  },
  {
    eventName: "Edit Expo",
    description:
      "Get ready to unleash your inner editing wizard at Edit Expo—the most thrilling content creation challenge! In this event, you’ll dive into a pool of photos and videos provided by the organizers, and it’s up to you to work your editing magic.  ",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumEditExpo,
    reglink: "",
  },
  {
    eventName: "Game Kraft",
    description:
      "A Gaming pitch battle for creative minds to present innovative game ideas. Participants will pitch their concept, including storyline, gameplay mechanics, and design vision, to a panel of judges. This event encourages originality and strategic thinking, making it perfect for beginners and aspiring game developers.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumGameCraft,
    reglink: "",
  },
  {
    eventName: "Robo Soccer",
    description:
      "Gear up for the ultimate showdown of brains and brawn—Robo Soccer! This action-packed event combines cutting-edge tech with the thrill of the beautiful game. Participants program their robots to dominate a miniature soccer arena, strategizing every kick, pass, and block. The goal? Outsmart, outplay, and outscore the competition!",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumRoboSoccer,
    reglink: "",
  },
  {
    eventName: "Spec-Moji",
    description:
      "In Competitive Programming, participants work solo or in pairs to solve a beginner-level algorithm problem within a time limit. In pairs, one codes while the other guides and debugs. Points are awarded for correctness and efficiency. Teamwork, problem-solving, and time management are key. The best solution wins.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumSpecMoji,
    reglink: "",
  },
];

export const events29 = [
  {
    eventName: "Designovate",
    description:
      "In Designovate, participants create innovative and practical solutions for a given problem using any tools or materials. Judging is based on creativity, functionality, and problem-solving effectiveness. Teams must present a clear concept, application, and impact while showcasing collaboration and originality.",
    date: "2025-02-15",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    clubName: "Zairza",
    day: "Day 2",
    image: Designovate,
    reglink: "",
  },
  {
    eventName: "Rescue Rangers",
    description:
      "Design bots to navigate a hurdle-filled track, scoring points at checkpoints. Falling bots return to the nearest checkpoint, losing points. Qualifiers are based on the fastest times, and the final round has a 10-minute limit. Bots must weigh under 5 kg. Finish fast, minimize damage, and maximize points.",
    date: "2025-02-15",
    startTime: "2:00 PM",
    endTime: "5:00 PM",
    clubName: "Zairza",
    day: "Day 2",
    image: ZairzaRescueRangers,
    reglink: "",
  },
  {
    eventName: "PVP Gaming",
    description:
      "In the PVP Gaming Tournament, participants compete in 1v1 and team games like Tekken 7, BGMI, and Valorant. 1v1 matches are best-of-three, while team games focus on kills, objectives, and strategy. Scoring is performance-based, and fair play, teamwork, and communication are crucial.",
    date: "2025-02-16",
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    clubName: "Zairza",
    day: "Day 2",
    image: ZairzaPVPGaming,
    reglink: "",
  },
  {
    eventName: "Wearable Tech",
    description:
      "In the Wearable Tech event, teams design a smartwatch prototype using provided sensors, a breadboard, and a microcontroller. The goal is to showcase features like health monitoring or fitness tracking within 60 minutes. Judging is based on creativity, functionality, and design. Innovate within the given resources!",
    date: "2025-02-16",
    startTime: "1:00 PM",
    endTime: "4:00 PM",
    clubName: "Zairza",
    day: "Day 2",
    image: ZairzaWearableTech,
    reglink: "",
  },
  {
    eventName: "Tech Meme",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Spectrum",
    day: "Day 2",
    image: SpectrumTechMeme,
    reglink: "",
  },
  {
    eventName: "Circuit Craft",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Energy",
    day: "Day 2",
    image: EnergyCircuitCraft,
    reglink: "",
  },
  {
    eventName: "Electrovia",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Energy",
    day: "Day 2",
    image: EnergyElectrovia,
    reglink: "",
  },
  {
    eventName: "Game Mania",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Energy",
    day: "Day 2",
    image: EnergyGameMania,
    reglink: "",
  },
  {
    eventName: "Line Follower",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Energy",
    day: "Day 2",
    image: EnergyLineFollower,
    reglink: "",
  },
  {
    eventName: "Water Rocket",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Aerospace",
    day: "Day 2",
    image: AerospaceWaterpoweredbottleRocket,
    reglink: "",
  },
  {
    eventName: "Airshow",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Aerospace",
    day: "Day 2",
    image: Aerospace76105RCAirplane,
    reglink: "",
  },
  {
    eventName: "Slingshot",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Aerospace",
    day: "Day 2",
    image: AerospaceSlingshotTech,
    reglink: "",
  },
];
export const events30 = [
  {
    eventName: "Uncanny Code Quest",
    description:
      "The Uncanny Code Quest is a coding challenge that takes you from basic tasks to mind-bending problems. With each level, you’ll face increasingly complex and unconventional coding challenges that test your skills, creativity, and problem-solving abilities. Prepare to tackle the unexpected and push your coding limits in this unique and exciting adventure!",
    date: "2025-02-15",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    clubName: "Spectrum",
    day: "Day 1",
    image: SpectrumUncannyCodeQuest,
    reglink: "",
  },
  {
    eventName: "Frame Forge",
    description: "Hands-on workshop to build and program robots.",
    date: "2025-02-15",
    startTime: "2:00 PM",
    endTime: "5:00 PM",
    clubName: "SAE",
    day: "Day 1",
    image: SAEFrameForge,
    reglink: "",
  },
  {
    eventName: "Lead The Beast",
    description: "A competitive programming contest for coding enthusiasts.",
    date: "2025-02-16",
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    clubName: "SAE",
    day: "Day 2",
    image: SAELeadTheBeast,
    reglink: "",
  },
  {
    eventName: "Tiny Whoop",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Aerospace",
    day: "Day 3",
    image: AerospaceTinyWhoop,
    reglink: "",
  },
  {
    eventName: "Wingman",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Aerospace",
    day: "Day 3",
    image: AerospaceWingman,
    reglink: "",
  },
  {
    eventName: "Bridge Making",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Civicon",
    day: "Day 3",
    image: CiviconBridgeMaking,
    reglink: "",
  },
  {
    eventName: "Canva Design",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Civicon",
    day: "Day 3",
    image: CiviconCanvaDesign,
    reglink: "",
  },
  {
    eventName: "Escape Room",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Civicon",
    day: "Day 3",
    image: CiviconEscapeRoom,
    reglink: "",
  },
  {
    eventName: "Where's The Mystery",
    description:
      "An evening filled with cultural performances, music, and dance.",
    date: "2025-02-17",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    clubName: "Civicon",
    day: "Day 3",
    image: CiviconWheresTheMystery,
    reglink: "",
  },
];

export const flagshipevents = [
  {
    eventName: "Robo Soccer",
    short:"A fun filled robotic soccer extravaganza",
    description:
      "Gear up for the ultimate showdown of brains and brawn—Robo Soccer! This action-packed event combines cutting-edge tech with the thrill of the beautiful game. Participants program their robots to dominate a miniature soccer arena, strategizing every kick, pass, and block. The goal? Outsmart, outplay, and outscore the competition!",
    date: "28-01-2025",
    startTime: "11:00 AM",
    endTime: "5:00 PM",
    clubName: "Spectrum",
    day: "Day-1",
    image: SpectrumRoboSoccer,
    logo:spectrumlogo,
    reglink: "https://forms.gle/ye78P578MBjapqAm9",
  },
  {
    eventName: "Rescue Rangers",
    short:"A thrilling race against time and obstacles",
    description:
      "Design bots to navigate a hurdle-filled track, scoring points at checkpoints. Falling bots return to the nearest checkpoint, losing points. Qualifiers are based on the fastest times, and the final round has a 10-minute limit. Bots must weigh under 5 kg. Finish fast, minimize damage, and maximize points.",
      date: "28-01-2025",
      startTime: "10:00 AM",
      endTime: "5:00 PM",
      clubName: "Zairza",
      logo: zairzalogo,
      day: "Day-1",
    image: RescueRangers,
    reglink: "https://forms.gle/vC5oreUZ9X5G47Uq6",
  },
  {
    eventName: "Line Follower",
    short:
      "Can Your Bot Crack the Maze? Is it the ultimate Maze Runner",
    description:"",
    date: "28-01-2025",
    startTime: "12:00 NOON",
    endTime: "5:00 PM",
    clubName: "Energy",
    day: "Day-1",
    image: EnergyLineFollower,
    reglink: "https://forms.gle/HBkfRni3UheUjgjG8",
    logo:energylogo
  },
  {
    eventName: "Lead The Beast",
    short: "A thrilling Race in the famed Blue Jay ATV",
    description: "Participants will be given a chance to drive the Blue Jay ATV and the fastest one wins",
    date: "28,29,30-01-2025",
    startTime: "10:00 AM",
    endTime: "5:00 PM",
    clubName: "SAE",
    day: "Day-1,2,3",
    image: SAELeadTheBeast,
    reglink: "https://forms.gle/mGmwNX6tMxstQMvv7",
    logo:saelogo
  },
  {
    eventName: "H2GO",
    short:
      "Take your Rocket to new Horizons",
    description: "Build Your Own Water Pressure propelled rocket can you beat the odds to reach the sky. Winner Takes it All",
    date: "29-01-2025",
    startTime: "1:00 PM",
    endTime: "5:00 PM",
    clubName: "Aerospace",
    day: "Day-2",
    image: AerospaceTech,
    reglink: "https://forms.gle/QXat9XnCmopcXTzn9",
    logo:aerospacelogo
  },
  {
    eventName: "Spark Your Thoughts",
    short:
      "A fun filled event to test your creativity and innovation",
    description: "A fun filled event to test your creativity and innovation",
    date: "Coming Soon",
    startTime: "Coming Soon",
    endTime: "Coming Soon",
    clubName: "Biozo",
    day: "Coming Soon",
    image: CompetitiveProgramming,
    reglink: "",
    logo:biozologo
  },
  {
    eventName: "Peek-a-boo",
    description:"",
    short:"a spooky event to test your courage and wit",
    date: "Coming Soon",
    startTime: "Coming Soon",
    endTime: "Coming Soon",
    clubName: "Biozo",
    day: "Coming Soon",
    image: CompetitiveProgramming,
    reglink: "",
    logo:biozologo
  },
  {
    eventName: "Frame",
    short:"Construct a Bridge that can withstand the force of nature",
    description: "Test your Engineering Skills in this competetion of durability and rigour. Teams have to build a bridge in a given time with ice cream sticks",
    date: "30-01-2025",
    startTime: "10:00 AM",
    endTime: "5:00 PM",
    clubName: "Civicon",
    day: "Day-3",
    image: CompetitiveProgramming,
    reglink: "",
    logo:civiconlogo
  },
];

// ad
